Repository hashicorp/syntax, pull requests merged in 2022-03, with the labels that each got.

#15 Release Automation
  .github/release.yml
  .github/workflows/release.yml
  RELEASE.md
Labels: build

#8 Fix highlighting for computed map keys
  syntaxes/hcl.tmGrammar.json
  tests/snapshot/hcl/issue809.hcl
  tests/snapshot/hcl/issue809.hcl.snap
Labels: bug

#17 Copy patterns from HCL grammar to Terraform grammar
  syntaxes/terraform.tmGrammar.json
  tests/snapshot/terraform/expressions_dynamic.tf.snap
  tests/snapshot/terraform/expressions_for.tf.snap
  tests/snapshot/terraform/expressions_functions.tf.snap
  tests/snapshot/terraform/expressions_splat.tf.snap
  tests/snapshot/terraform/expressions_strings.tf.snap
  tests/snapshot/terraform/issue927.tf.snap
  tests/snapshot/terraform/modules.tf.snap
  tests/snapshot/terraform/variables_input.tf.snap
  tests/snapshot/terraform/variables_local.tf.snap
Labels: bug

#18 Update scope for HCL function highlighting
  syntaxes/hcl.tmGrammar.json
  tests/snapshot/hcl/basic.hcl.snap
  tests/snapshot/hcl/expressions_conditional.hcl.snap
  tests/snapshot/hcl/expressions_for.hcl.snap
  tests/snapshot/hcl/expressions_functions.hcl.snap
  tests/snapshot/hcl/issue941.hcl.snap
  tests/snapshot/hcl/variables_input.hcl.snap
  tests/snapshot/hcl/variables_local.hcl.snap
Labels: enhancement

#23 Add missing grammar updates to Terraform
  syntaxes/terraform.tmGrammar.json
  tests/snapshot/terraform/issue809.tf
  tests/snapshot/terraform/issue809.tf.snap
  tests/snapshot/terraform/issue941.tf
  tests/snapshot/terraform/issue941.tf.snap
Labels: bug

#20 Fix highlighting of nested complex types
  syntaxes/hcl.tmGrammar.json
  syntaxes/terraform.tmGrammar.json
  tests/snapshot/hcl/issue19.hcl
  tests/snapshot/hcl/issue19.hcl.snap
  tests/snapshot/hcl/variables_input.hcl.snap
  tests/snapshot/terraform/issue19.tf
  tests/snapshot/terraform/issue19.tf.snap
  tests/snapshot/terraform/variables_input.tf.snap
Labels: bug

#29 prepare release v0.2.0
  package-lock.json
  package.json
Labels: build

#22 Build Syntaxes
  builder/go.mod
  builder/go.sum
  builder/main.go
  src/_main.yml
  src/hcl.yml
  src/terraform.yml
  syntaxes/hcl.tmGrammar.json
  syntaxes/terraform.tmGrammar.json
Labels: build
